export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};
import { Poppins } from "next/font/google";
import "./style.scss";
const poppins = Poppins({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-poppins",
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className={`${poppins.variable}`}>
            <body>{children}</body>
        </html>
    );
}
